### PR TITLE
Update WLPManagedContainer.java

### PR DESCRIPTION
**Pull request by brutif**
increase read  buffer size so noisy tests do not deadlock

### CODE REVIEW

**Comment by gpoul** [comment]
I don't grasp how this might deadlock; can you reproduce the issue somehow? Looking at the Javadoc at https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[]) I don't think the size of the array should have much effect on whether the build succeeds or not, although it might be slower.

**Comment by brutif** [comment]
I agree there's more to it than just waiting to read on the stream,  something else is going on, perhaps along the lines of  https://stackoverflow.com/questions/38098494/why-processbuilder-in-java-hangs-after-5-mins.    


It's been intermittent.  32k might be a bit much,  I'll retest and see if a 1 or 2k buffer is sufficient, and if I can grab a thread dump when it hangs.  What I observed was in tests where there was a lot of Arquillian or Liberty output in the stream, lockup occurred occasionally, and that ceased after this change.   "Quiet" tests ran fine (on Windows7).

**Comment by gpoul** [comment]
It would be great to get some more details regarding the issue you're seeing; did this only happen to you on Windows or on other platforms as well?

**Comment by brutif** [comment]
I've only run on windows so far, I can even get it to happen with a larger buffer, but not as frequently. Threaddumps show arquillian waiting to read, but Liberty waiting to write, so something has become disconnected in the middle here..

arquillian: 
`Thread 24: (state = IN_NATIVE)
 - java.io.FileInputStream.readBytes(byte[], int, int) @bci=0 (Interpreted frame)
 - java.io.FileInputStream.read(byte[], int, int) @bci=4, line=255 (Interpreted frame)
 - java.io.BufferedInputStream.read1(byte[], int, int) @bci=39, line=284 (Compiled frame)
 - java.io.BufferedInputStream.read(byte[], int, int) @bci=49, line=345 (Compiled frame)
 - java.io.FilterInputStream.read(byte[]) @bci=5, line=107 (Compiled frame)
 - org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer$ConsoleConsumer.run() @bci=30, line=988 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)`

In liberty the test is hung trying to log output
`Thread 33: (state = IN_NATIVE)
 - java.io.FileOutputStream.writeBytes(byte[], int, int, boolean) @bci=0 (Compiled frame; information may be imprecise)
 - java.io.FileOutputStream.write(byte[], int, int) @bci=8, line=326 (Compiled frame)
 - java.io.BufferedOutputStream.write(byte[], int, int) @bci=20, line=122 (Compiled frame)
 - java.io.PrintStream.write(byte[], int, int) @bci=16, line=480 (Compiled frame)
 - sun.nio.cs.StreamEncoder.writeBytes() @bci=120, line=221 (Compiled frame)
 - sun.nio.cs.StreamEncoder.implFlushBuffer() @bci=11, line=291 (Compiled frame)
 - sun.nio.cs.StreamEncoder.flushBuffer() @bci=15, line=104 (Compiled frame)
 - java.io.OutputStreamWriter.flushBuffer() @bci=4, line=185 (Compiled frame)
 - java.io.PrintStream.write(java.lang.String) @bci=27, line=527 (Compiled frame)
 - java.io.PrintStream.print(java.lang.String) @bci=9, line=669 (Compiled frame)
 - java.io.PrintStream.println(java.lang.String) @bci=6, line=806 (Compiled frame)
 - com.ibm.ws.logging.internal.impl.BaseTraceService.writeStreamOutput(com.ibm.ws.logging.internal.impl.BaseTraceService$SystemLogHolder, java.lang.String, boolean) @bci=37, line=870 (Interpreted frame)
 - com.ibm.ws.logging.internal.impl.BaseTraceService.publishLogRecord(java.util.logging.LogRecord) @bci=236, line=589 (Compiled frame)
 - com.ibm.ws.logging.internal.impl.BaseTraceService.error(com.ibm.websphere.ras.TraceComponent, java.lang.String, java.lang.Object[]) @bci=14, line=319 (Interpreted frame)
 - com.ibm.websphere.ras.Tr.error(com.ibm.websphere.ras.TraceComponent, java.lang.String, java.lang.Object[]) @bci=6, line=485 (Interpreted frame)
 - com.ibm.ws.security.mp.jwt.tai.MicroProfileJwtTAI.handleMicroProfileJwtValidation(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse, com.ibm.ws.security.mp.jwt.MicroProfileJwtConfig, java.lang.String) @bci=50, line=260 (Interpreted frame)`

investigation continues...

**Comment by brutif** [comment]
I can avoid this by configuring liberty logging to not write anything to it's console
 ``<logging consoleLogLevel="off" copySystemStreams="false"`` />

**Comment by gpoul** [comment]
Just for some sanity checking to make sure I don't miss anything. The ProcessBuilder was called with redirectErrorStream(true) so we should only have one stream buffer; at least logically for us; not sure what the native implementation then looks like to not cause this to lock up. And we seem to be stuck in the InputStream.read() which in this case is supposed to block unless it reaches EOF or reads at least 1 byte. Whereas the Liberty process is stuck in the write() that is supposed to write the bytes to the OS buffer that we're reading and not really block unless this buffer is full. So for some reason it seems Liberty can't write to the OS buffer because it is full, but we can't read as there is not a single byte coming out of it.

Is this observation correct or am I missing something?

So this should be easy to reproduce if we just switch on full debugging, right? :)

I'm not saying this is related to it, but which JVM and -fullversion are you using?

**Comment by gpoul** [comment]
@stuartwdouglas / @galderz you worked on [this code on the wildfly container implementation](https://github.com/wildfly/wildfly-arquillian/blame/9faa9e530dc5e8e88e1e6035d20803763ff13022/container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java#L360); do you think you could review this PR comment stream and see whether you might have any insight or thoughts to add?

**Comment by brutif** [comment]
That sounds correct.

This happened with an Oracle JVM 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

but it also happens with an IBM java8 jvm.   Oracle has the handy jstack tool to get a thread dump.

It might be some weird windows native code thing, in that case, where would be a good spot to document the workaround to server.xml?

**Comment by gpoul** [comment]
Have you had a chance to test whether increasing the debug level will make this happen more frequently?

Maybe someone else has an idea as well in the mean time and I'll try to reproduce this next weekend and see whether I can see anything.

**Comment by brutif** [comment]
@gpoul  how do I switch it on full debugging?

For what it's worth I wrote a servlet that dumped 100k to the console in it's init method, that could -not- reproduce the issue.

**Comment by gpoul** [comment]
@brutif I was thinking along the lines of configuring the trace to *=all and tracefilename="stdout" as that should put a lot of trace of liberty to stdout. But I'll try to test that on the weekend on my end as well

**Comment by galderz** [comment]
I worked very briefly in this code, I doubt I can add any meaningful input here.

**Comment by brutif** [comment]
I'm going to close this.  I see the fork I'm using internally is missing this in WlpManagedContainer: 
pb.redirectErrorStream(true);

When I add that it quits hanging.  @gpoul , thanks for looking at this.  Sorry for the false alarm.

**Comment by gpoul** [comment]
@brutif ok, makes sense that it hangs in this case... good that you found it.

**Pull request closed without merging**
